openapi: 3.0.0
servers:
  - url: https://virtserver.swaggerhub.com/FaniryKeziah/PROG3_TD2/1.0.0
info:
  version: "latest"
  title: PROG3 - TD1
paths:
  /match:
    get:
      tags:
        - Match
      summary: get all match
      operationId: getMatch
      responses:
        '200':
          description: List of match
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
    
  /team:
    get:
      tags:
        - Team
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /player:
    get:
      tags:
        - Players
      summary: get all players
      operationId: getPlayer
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Players'
        '500':
          description: Internal server error
    
components:
  schemas:
    Match:
      type: object
      properties:
        oneteam:
          type: string
        otherteam:
          type: string 
        datetime:
          type: string
    Team:
      type: object
      properties:
        Players:
          type: object 
        Sponsor:
          type: object  
    Players:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    
    